# Generated by Django 5.2.5 on 2025-08-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_material_news_remove_studenthonor_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='material.level'),
        ),
    ]
