# Generated by Django 5.2.5 on 2025-08-18 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_remove_quiz_correct_answer_remove_quiz_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-upvotes', '-created_at']},
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('truefalse', 'True / False')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='material.level'),
        ),
        migrations.AlterField(
            model_name='note',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='material.level'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='material.level'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
